### ISSUE TITLE
When using elasticsearch 5.0+ JestElasticsearchTemplate.refresh(String indexName) is broken

### ISSUE THREAD

**Issue by joechev** [VanRoy/spring-data-jest#25] opened 2017-02-23 22:18 UTC
Elasticsearch REST API has been changed as of 5.0 to do strict validation of request parameters.  Previously invalid request parameters would be ignored silently.  Now, they cause the request to fail.

In JestElasticsearchTemplate.refresh(String indexName) the request being built sends the refresh request parameter which is used for document refresh, not for index refresh, and thus it fails.  The refresh request parameter should be removed for index refreshes.

**Comment by VanRoy** [comment] 2017-03-03 21:06
Hi @joechev , at this time neither SpringDataElasticsearch nor Jest support ES 5.x.

Even with the fix on refresh, many error remains on unit test.

I will investigate to find the best option to make SpringDataJest compatible with ES 5.x.

Thanks.
Julien.

**Comment by robmoore** [comment] 2017-05-24 22:18
I just noticed there is a pull request related to this issue. Just wondering it hasn't been accepted because the change would cause issues with pre 5.x versions of ES?

**Comment by VanRoy** [comment] 2017-05-27 15:52
Hi @robmoore , for now i am waiting for next release of SearchBox Jest that will support ES 5.0 to finalise the implementation.
Stay in touch :)

**Comment by rzimmer** [comment] 2017-05-31 16:42
@VanRoy You mean the

**Comment by VanRoy** [comment] 2017-06-03 08:11
Hi @rzimmer , I just finished the first iteration of ES 5.x support. You can try the 3.0.0-SNAPSHOT version available on branch 3.x

Feel free to try the next release and please send me your feedback if you can.

Thanks for your help.

**Comment by rzimmer** [comment] 2017-06-06 07:15
Great, thanks for the heads up! Will give it a try as soon as I can.

**Comment by jayeshgangadharan** [comment] 2017-06-07 16:07
Great. I'll try this as well. Thanks @VanRoy

**Comment by ernsyn** [comment] 2017-06-12 13:39
Cool! I was facing the same issue. I'm going to test the 3.0.0-SNAPSHOT version out. Thanbks @VanRoy.

**Comment by ernsyn** [comment] 2017-06-12 14:21
Hi @VanRoy, I tried building 3.0.0-SNAPSHOT but encountered some unit test error for the Spring Data jest project. Building it with -DskipTests=true helps tho but when I added the SNAPSHOT to my Spring Boot project (using JHipster), I get a Caused by: java.lang.NoClassDefFoundError: org/elasticsearch/node/NodeValidationException.

Any ideas?

**Comment by jayeshgangadharan** [comment] 2017-06-12 15:08
@ernsyn see if you have right dependencies?

spring data jest - 3.0.0-SNAPSHOT
spring boot - 2.0.0-BUILD-SNAPSHOT
spring data elasticsearch - 3.0.0-BUILD-SNAPSHOT
jest - 5.3.2
elasticsearch - 5.3.2

**Comment by ernsyn** [comment] 2017-06-13 05:17
Hi @jayeshgangadharan. 

I'm actually using this project with JHipster and I followed the answer provided in https://stackoverflow.com/questions/39623238/setting-up-bonsai-elasticsearch-in-jhipster-heroku. 

I cloned the repository and build the SNAPSHOT locally and then modified the dependency to 

    <dependency>
        <groupId>com.github.vanroy</groupId>
        <artifactId>spring-boot-starter-data-jest</artifactId>
        <version>3.0.0-SNAPSHOT</version>
    </dependency>

However, somehow when running mvn dependency:tree, I can see that the old version of Jest is still being used. I then added the following dependency management.

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.data</groupId>
		<artifactId>spring-data-elasticsearch</artifactId>
		<version>3.0.0.BUILD-SNAPSHOT</version>
		<exclusions>
		    <exclusion>
		        <groupId>org.elasticsearch</groupId>
			<artifactId>elasticsearch</artifactId>
	            </exclusion>
	        </exclusions>
            </dependency>

	    <dependency>
	        <groupId>org.elasticsearch</groupId>
		<artifactId>elasticsearch</artifactId>
		<version>5.3.2</version>
	    </dependency>

	    <dependency>
	        <groupId>io.searchbox</groupId>
		<artifactId>jest</artifactId>
		<version>5.3.2</version>
		<exclusions>
		    <exclusion>
		        <groupId>commons-logging</groupId>
			<artifactId>commons-logging</artifactId>
		    </exclusion>
	        </exclusions>
	    </dependency>
        </dependencies>
    </dependencyManagement>

Now, when I start the application, I get the following exception.

`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userSearchRepository': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/data/querydsl/QuerydslUtils
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 22 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/data/querydsl/QuerydslUtils
	at org.springframework.data.elasticsearch.repository.support.ElasticsearchRepositoryFactory.isQueryDslRepository(ElasticsearchRepositoryFactory.java:95)
	at org.springframework.data.elasticsearch.repository.support.ElasticsearchRepositoryFactory.getRepositoryBaseClass(ElasticsearchRepositoryFactory.java:79)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepositoryInformation(RepositoryFactorySupport.java:253)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:195)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.initAndReturn(RepositoryFactoryBeanSupport.java:277)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:263)
	at org.springframework.data.elasticsearch.repository.support.ElasticsearchRepositoryFactoryBean.afterPropertiesSet(ElasticsearchRepositoryFactoryBean.java:67)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 33 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.data.querydsl.QuerydslUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 common frames omitted`

Do you happen to have any idea why I'm facing this problem? If you do, please advise what I did wrong. Thanks!

**Comment by ernsyn** [comment] 2017-06-13 08:36
Sorry for spamming. Just to share my findings. The exception I'm getting above can also be simulated with the sample aws application.

**Comment by VanRoy** [comment] 2017-06-13 19:18
Hi @ernsyn , you need to move to :

spring boot - 2.0.0-BUILD-SNAPSHOT
spring data elasticsearch - 3.0.0-BUILD-SNAPSHOT
jest - 5.3.2

Actually required by Spring Data Elasticsearch 3.0.0

**Comment by ernsyn** [comment] 2017-06-14 08:18
Hi @VanRoy,

Yup, I found out the same as well when I was playing around with the sample aws project. Unfortunately I can't move to that at the moment so I think I'll stick with the older version of ES for now. 

Thanks for the support guys!

**Comment by ashleyfrieze** [comment] 2017-07-22 13:40
Do you have a release date in mind for v3?

**Comment by VanRoy** [comment] 2017-07-24 17:25
@ashleyfrieze , juste after Spring 5.x and Spring Data 2.x release. I guess in September.

**Comment by ashleyfrieze** [comment] 2017-07-24 18:59
@VanRoy Thanks for the answer and the great product!

**Comment by VanRoy** [comment] 2017-10-05 19:11
Released in 3.0.0

**Closed by VanRoy** 2017-10-05 19:11 UTC
Labels: enhancement
